version: "3.9"

services:
  qrcode:
    build:
      context: .
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    image: qrcode:1.0.0.4
    container_name: qrcode
    restart: "unless-stopped"
    networks:
      - qrcode_network
      - traefik-proxy
    ports:
    #  - "8080:80" # Originally at 8080
      - "80" #take advantage of Traefik
    user: "${PUID}:${PGID}"
    environment:
      ADMIN_USER: "superadmin"
      ADMIN_PASSWORD: "superadmin"
      DATABASE_HOST: "mariadb"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "qrcode"
      DATABASE_USER: "qrcode"
      DATABASE_PASSWORD: "changeme"
      DATABASE_CHARSET: "utf8"
    volumes:
      - ./data/app/config:/var/www/html/config
      - ./data/app/saved_qrcode:/var/www/html/saved_qrcode
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrcode.entrypoints=http"
      - "traefik.http.routers.qrcode.rule=Host(`qr.$DOMAINNAME`)"
      - "traefik.http.routers.qrcode.middlewares=traefik-https-redirect"
      - "traefik.http.routers.qrcode-secure.entrypoints=https"
      - "traefik.http.routers.qrcode-secure.rule=Host(`qr.$DOMAINNAME`)"
      - "traefik.http.routers.qrcode-secure.tls=true"
      - "traefik.http.routers.qrcode-secure.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.qrcode-secure.service=qrcode-docker"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: "unless-stopped"
    environment:
      MARIADB_ROOT_PASSWORD: "changeme"
      MARIADB_DATABASE: "qrcode"
      MARIADB_USER: "qrcode"
      MARIADB_PASSWORD: "changeme"
    networks:
      - qrcode_network
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306

########################### networks
networks:
  qrcode_network:
    driver: bridge
    name: qrcode
  traefik-proxy:
    external: true
